name: escodegen
version: 0.0.1
category: Language
synopsis: Parser/generator of ECMAScript, backed by esprima/escodegen on Node.js
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/escodegen

custom-setup:
  dependencies:
    - base
    - binary
    - Cabal
    - filepath
    - process

extra-source-files:
  - LICENSE
  - README.md
  - CHANGELOG.md

data-files:
  - escodegen-server/package.json
  - escodegen-server/server.js

ghc-options: -Wall

dependencies:
  - aeson
  - base >= 4.9 && < 5
  - bytestring
  - http-conduit

library:
  source-dirs: src
